# type: ignore

from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


class ServerConfig(BaseModel):
    """Server Confgiguration."""

    host: str
    port: int
    transport: str
    url: str


class PlannerTask(BaseModel):
    """Represents a single task generated by the Planner."""
 
    id: int = Field(description='Sequential ID for the task.')
 
    # agent: Literal['music_catalog_agent', 'invoice_info_agent'] = Field(
    #     description=(
    #         'The agent responsible for executing this task. '
    #         'Use music_catalog_agent for anything related to music, artists, albums, tracks, genres, or playlists. '
    #         'Use invoice_info_agent for anything related to invoices, billing, purchases, unit prices, or employee support.'
    #     )
    # )
 
    # query: str = Field(
    #     description='The exact query to send to the assigned agent.'
    # )
 
    description: str = Field(
        description='Clear human-readable description of what this task does.'
    )
 
    status: (
        Any
        | Literal[
            'input_required',
            'completed',
            'error',
            'pending',
            'incomplete',
            'todo',
            'not_started',
        ]
        | None
    ) = Field(description='Status of the task.', default='not_started')


class TaskList(BaseModel):
    """Output schema for the Planner Agent."""

    original_query: str | None = Field(
        description='The original user query for context.'
    )

    tasks: list[PlannerTask] = Field(
        description='A list of tasks to be executed sequentially.'
    )


class AgentResponse(BaseModel):
    """Output schema for the Agent."""

    content: str | dict = Field(description='The content of the response.')
    is_task_complete: bool = Field(description='Whether the task is complete.')
    require_user_input: bool = Field(
        description='Whether the agent requires user input.'
    )